### ISSUE TITLE
Update libsass

### ISSUE THREAD

**Issue by dtrunk90** [kjdev/apache-mod-sass#3]
Hello,

I tried to do it on my own, but always getting errors running `make`:
```
In file included from mod_sass.c:28:0:
libsass/include/sass/interface.h:9:23: fatal error: sass/base.h: No such file or directory
 #include <sass/base.h>
                       ^
compilation terminated.
```

It would be great if you could take a look into my fork and give me some help and/or update libsass.
I'm not really familiar with C++.

**Comment by kjdev** [comment]
It did not correspond to the latest libsass.

Therefore please verify has been adjusted to be able to build.

**Comment by dtrunk90** [comment]
I don't get why `sass/base.h` can't be found.
The folder structure has changed.
I already did some adjustments.
As I'm not familiar with C(++) I would adjust step by step.

**Comment by kjdev** [comment]
Please try to specify the include directory of libsass the Makefile of CPPFLAGS (`-Ilibsass/include`)

* configure.ac, Makefile.am
   https://github.com/kjdev/apache-mod-sass/blob/master/configure.ac#L79
   https://github.com/kjdev/apache-mod-sass/blob/master/Makefile.am#L53

* Makefile
   ```
   mod_sass_la_CPPFLAGS =   -DLINUX -D_REENTRANT -D_GNU_SOURCE -std=c++11 -I/usr/include/httpd  -I/usr/include/apr-1  -Ilibsass/include
   ```

**Comment by dtrunk90** [comment]
Oh. I've missed that line. Thank you. I'll do more work on this and make a pull request.
